version: "3.7"
services:
  api_service:
    build: .
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - mysql_db
      - app
    command: sh -c './wait-for mysql_db:3306 -- npm start'
  app:
    build: ./app
    links:
      - mysql_db
    ports:
      - 5001:80
  mysql_db:
    image: "mysql:8.0"
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: movieadvisor_db
      MYSQL_USER: movieadvisor_dev
      MYSQL_PASSWORD: nE5kMc7JCGNqwDQM
      MYSQL_ROOT_PASSWORD: nE5kMc7JCGNqwDQM